---

- name: Add apt key for newest tor
  apt_key:
    keyserver: keys.gnupg.net
    id: '886DDD89'
  become: True
  become_method: sudo

- name: Add newest tor
  apt_repository:
    repo: "deb http://deb.torproject.org/torproject.org/ {{ ansible_distribution_release }} main"
    update_cache: True
  become: True
  become_method: sudo


- name: Install tor
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - tor
    - torsocks
  become: True
  become_method: sudo

- name: Get onion url
  set_fact:
    onionurl: "{% for i in hostvars %}{% if hostvars[i]['torhostrv'] is defined %}{{ hostvars[i]['torhostrv']['stdout'] }}{% endif %}{% endfor %}"

- name: Filter servers
  set_fact:
    serverlist: "{{ hostvars|list }}"

- name: Create connect file
  copy:
    dest: "{{ playbook_dir }}/onionssh_{{ item }}.bash"
    mode: 0744
    content: |
      #!/bin/bash
      torsocks ssh $1@{{ hostvars[item]['torhostrv']['stdout'] }}
  with_items: "{{ serverlist }}"
  when: "{{ 'torhostrv' in hostvars[item] }}"
  ignore_errors: True


